services:
  app:
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8000:8000
    secrets:
      - django_secret_key
      - postgres_password
    volumes:
      - .:/app

  kafka:
    image: apache/kafka
    healthcheck:
      start_interval: 1s
      start_period: 5s
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - 9092:9092

  kafka-consumer:
    build: .
    command: python manage.py runkafkaconsumer
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    secrets:
      - django_secret_key
      - postgres_password
    volumes:
      - .:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      start_interval: 1s
      start_period: 5s
      test: pg_isready -U postgres -d postgres
    ports:
      - 5432:5432
    secrets:
      - postgres_password

  redis:
    image: redis
    healthcheck:
      start_interval: 1s
      start_period: 5s
      test: redis-cli ping
    ports:
      - 6379:6379

secrets:
  django_secret_key:
    file: django_secret_key
  postgres_password:
    file: postgres_password
